num = 1
while num <= 21:
    print(num, end=",")
    num += 2
num = 2
while num <= 17:
    print(num, end=",")
    num += 3
num = 100
while num >= -90:
    print(num, end=",")
    num -= 10
num = -30
while num <= 30:
    print(num, end=",")
    num += 10
num = 15
while num <= 55:
    print(num, end=",")
    num += 8
    